# PagesCMS Configuration for OmixAI Website
# https://pagescms.org/docs/configuration
# Structure: field > { ko, en } for bilingual content

media:
  input: public
  output: /

content:
  # Common (shared across all pages)
  - name: common
    label: Common (Nav, Footer)
    type: file
    path: src/content/common.json
    format: json
    fields:
      - name: meta
        label: Meta Information
        type: object
        fields:
          - name: title
            label: Site Title
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
      - name: nav
        label: Navigation
        type: object
        fields:
          - name: services
            label: Services
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: resources
            label: Resources
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: about
            label: About Us
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: contact
            label: Contact
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: cta
            label: CTA Button
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: orderNow
            label: Order Now Button
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
      - name: footer
        label: Footer
        type: object
        fields:
          - name: tagline
            label: Tagline
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }

  # Landing Page
  - name: landing
    label: Landing Page
    type: file
    path: src/content/landing.json
    format: json
    fields:
      - name: kpis
        label: KPIs (Key Stats)
        type: object
        fields:
          - name: items
            label: KPI Items
            type: object
            list: true
            fields:
              - { name: value, label: Value (e.g. "10,000"), type: string }
              - name: label
                label: Label
                type: object
                fields:
                  - { name: ko, label: Korean, type: string }
                  - { name: en, label: English, type: string }
      - name: hero
        label: Hero Section
        type: object
        fields:
          - name: title
            label: Title
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: subtitle
            label: Subtitle
            type: object
            fields:
              - { name: ko, label: Korean, type: text }
              - { name: en, label: English, type: text }
          - name: description
            label: Description
            type: object
            fields:
              - { name: ko, label: Korean, type: text }
              - { name: en, label: English, type: text }
          - name: cta
            label: CTA Text
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
      - name: services
        label: Services Section
        type: object
        fields:
          - name: title
            label: Section Title
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: items
            label: Service Items
            type: object
            list: true
            fields:
              - { name: icon, label: Icon (Emoji), type: string }
              - name: title
                label: Title
                type: object
                fields:
                  - { name: ko, label: Korean, type: string }
                  - { name: en, label: English, type: string }
              - { name: slug, label: URL Slug, type: string }
      - name: testimonials
        label: Testimonials Section
        type: object
        fields:
          - name: title
            label: Section Title
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: items
            label: Testimonials
            type: object
            list: true
            fields:
              - name: quote
                label: Quote
                type: object
                fields:
                  - { name: ko, label: Korean, type: text }
                  - { name: en, label: English, type: text }
              - { name: author, label: Author Name, type: string }
              - { name: institution, label: Institution, type: string }
      - name: howItWorks
        label: How It Works Section
        type: object
        fields:
          - name: title
            label: Section Title
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: steps
            label: Steps
            type: object
            list: true
            fields:
              - { name: number, label: Step Number, type: string }
              - name: title
                label: Title
                type: object
                fields:
                  - { name: ko, label: Korean, type: string }
                  - { name: en, label: English, type: string }
              - name: description
                label: Description
                type: object
                fields:
                  - { name: ko, label: Korean, type: text }
                  - { name: en, label: English, type: text }

  # Resources Page
  - name: resources
    label: Resources Page
    type: file
    path: src/content/resources.json
    format: json
    fields:
      - name: title
        label: Page Title
        type: object
        fields:
          - { name: ko, label: Korean, type: string }
          - { name: en, label: English, type: string }
      - name: subtitle
        label: Page Subtitle
        type: object
        fields:
          - { name: ko, label: Korean, type: string }
          - { name: en, label: English, type: string }
      - name: faq
        label: FAQ Section
        type: object
        fields:
          - name: title
            label: FAQ Title
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: ordering
            label: Ordering & Pricing
            type: object
            fields:
              - name: title
                label: Section Title
                type: object
                fields:
                  - { name: ko, label: Korean, type: string }
                  - { name: en, label: English, type: string }
              - name: items
                label: FAQ Items
                type: object
                list: true
                fields:
                  - name: question
                    label: Question
                    type: object
                    fields:
                      - { name: ko, label: Korean, type: string }
                      - { name: en, label: English, type: string }
                  - name: answer
                    label: Answer
                    type: object
                    fields:
                      - { name: ko, label: Korean, type: text }
                      - { name: en, label: English, type: text }
          - name: samplePrep
            label: Sample Preparation
            type: object
            fields:
              - name: title
                label: Section Title
                type: object
                fields:
                  - { name: ko, label: Korean, type: string }
                  - { name: en, label: English, type: string }
              - name: items
                label: FAQ Items
                type: object
                list: true
                fields:
                  - name: question
                    label: Question
                    type: object
                    fields:
                      - { name: ko, label: Korean, type: string }
                      - { name: en, label: English, type: string }
                  - name: answer
                    label: Answer
                    type: object
                    fields:
                      - { name: ko, label: Korean, type: text }
                      - { name: en, label: English, type: text }
          - name: technical
            label: Technical Details
            type: object
            fields:
              - name: title
                label: Section Title
                type: object
                fields:
                  - { name: ko, label: Korean, type: string }
                  - { name: en, label: English, type: string }
              - name: items
                label: FAQ Items
                type: object
                list: true
                fields:
                  - name: question
                    label: Question
                    type: object
                    fields:
                      - { name: ko, label: Korean, type: string }
                      - { name: en, label: English, type: string }
                  - name: answer
                    label: Answer
                    type: object
                    fields:
                      - { name: ko, label: Korean, type: text }
                      - { name: en, label: English, type: text }

  # About Page
  - name: about
    label: About Page
    type: file
    path: src/content/about.json
    format: json
    fields:
      - name: title
        label: Page Title
        type: object
        fields:
          - { name: ko, label: Korean, type: string }
          - { name: en, label: English, type: string }
      - name: subtitle
        label: Subtitle
        type: object
        fields:
          - { name: ko, label: Korean, type: string }
          - { name: en, label: English, type: string }
      - name: team
        label: Team Members
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - { name: title, label: Job Title, type: string }
          - { name: photo, label: Photo Path, type: string }
          - name: education
            label: Education
            type: object
            fields:
              - { name: ko, label: Korean, type: string, list: true }
              - { name: en, label: English, type: string, list: true }
          - name: experience
            label: Experience
            type: object
            fields:
              - { name: ko, label: Korean, type: string, list: true }
              - { name: en, label: English, type: string, list: true }
      - name: investors
        label: Investors
        type: object
        fields:
          - name: title
            label: Section Title
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: list
            label: Investor List
            type: object
            list: true
            fields:
              - { name: name, label: Investor Name, type: string }
              - { name: logo, label: Logo Path, type: string }
      - name: timeline
        label: Timeline
        type: object
        fields:
          - name: title
            label: Section Title
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: milestones
            label: Milestones
            type: object
            list: true
            fields:
              - name: date
                label: Date
                type: object
                fields:
                  - { name: ko, label: Korean, type: string }
                  - { name: en, label: English, type: string }
              - name: event
                label: Event Description
                type: object
                fields:
                  - { name: ko, label: Korean, type: string }
                  - { name: en, label: English, type: string }

  # Contact Page
  - name: contact
    label: Contact Page
    type: file
    path: src/content/contact.json
    format: json
    fields:
      - name: title
        label: Page Title
        type: object
        fields:
          - { name: ko, label: Korean, type: string }
          - { name: en, label: English, type: string }
      - name: email
        label: Email
        type: object
        fields:
          - name: label
            label: Label
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - { name: value, label: Email Address, type: string }
      - name: address
        label: Address
        type: object
        fields:
          - name: label
            label: Label
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: value
            label: Address Line 1
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: detail
            label: Address Line 2
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
      - name: map
        label: Map
        type: object
        fields:
          - name: title
            label: Map Section Title
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }

  # Notices/Announcements (bilingual collection)
  - name: notices
    label: Notices
    type: collection
    path: src/content/notices
    format: json
    filename: '{slug}.json'
    exclude: [.DS_Store]
    view:
      primary: slug
      fields: [date, active]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: date, label: Date (YYYY-MM-DD), type: string, required: true }
      - { name: active, label: Show in Banner, type: boolean }
      - name: title
        label: Notice Title
        type: object
        fields:
          - { name: ko, label: Korean, type: string }
          - { name: en, label: English, type: string }
      - name: content
        label: Content
        type: object
        fields:
          - { name: ko, label: Korean, type: text }
          - { name: en, label: English, type: text }

  # Service Pages (bilingual collection)
  - name: services
    label: Services
    type: collection
    path: src/content/services
    format: json
    filename: '{slug}.json'
    exclude: [.DS_Store]
    view:
      primary: slug
      fields: [slug, title]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - name: title
        label: Service Title
        type: object
        fields:
          - { name: ko, label: Korean, type: string }
          - { name: en, label: English, type: string }
      - name: subtitle
        label: Subtitle
        type: object
        fields:
          - { name: ko, label: Korean, type: string }
          - { name: en, label: English, type: string }
      - name: description
        label: Description
        type: object
        fields:
          - { name: ko, label: Korean, type: text }
          - { name: en, label: English, type: text }
      - name: features
        label: Features
        type: object
        list: true
        fields:
          - name: title
            label: Feature Title
            type: object
            fields:
              - { name: ko, label: Korean, type: string }
              - { name: en, label: English, type: string }
          - name: description
            label: Feature Description
            type: object
            fields:
              - { name: ko, label: Korean, type: text }
              - { name: en, label: English, type: text }
